### PR TITLE
Support for STM32G4 targets

### PR DESCRIPTION
**Pull request by rosterloh**
Flash definitions for STM32G4 devices and Nucleo boards

Signed-off-by: Richard Osterloh <richard.osterloh@gmail.com>

### CODE REVIEW

**Comment by rosterloh** [comment]
It hasn't no

**Comment by galak** [comment]
> It hasn't no

Would appreciate if you can do that first.

**Comment by rosterloh** [comment]
There is this one currently open http://openocd.zylin.com/#/c/4807 

I did this work to test my PRs the have been submitted to zephyr main repo. To be quite honest I don't have the time to go through all of these reviews. I thought I'd be helpful and give back.

**Comment by galak** [comment]
> There is this one currently open http://openocd.zylin.com/#/c/4807
> 
> I did this work to test my PRs the have been submitted to zephyr main repo. To be quite honest I don't have the time to go through all of these reviews. I thought I'd be helpful and give back.

Do your changes differ from that upstream change?

I'm find with pulling something in for STM32G4 just want to understand what's the source, and what the long term maintenance might be for it.

**Comment by rosterloh** [comment]
@galak The upstream PR adds the G0 and G4 devices in with the L4 series which I don't think is a great idea. I have isolated the G4 but I'm happy to wait for the upstream merge and test it.

**Comment by galak** [comment]
closing as stm32g4 is merged upstream.

**Pull request closed without merging**
