### PR TITLE
add support for Nuvoton numicro M4 series

### PR DESCRIPTION
**Pull request by ssekar15**
add support for Nu-Link (Nuvoton ICE) over usb and Numicro M4 series.

- new part numbers for M480.
- tcl configuration file for Nuvoton M4 series.

Original work is fetched from Nuvoton github.
Made code cleanup, fixed merge conflicts, compile and runtime issues.

Signed-off-by: Saravanan Sekar <saravanan@linumiz.com>

### CODE REVIEW

**Comment by carlescufi** [comment]
@ssekar15 have you sent this patch upstream?
@MaureenHelm @galak do we take downstream opencd patches?

**Comment by ssekar15** [comment]
@carlescufi I am preparing to send to openocd upstream.

**Comment by ssekar15** [comment]
@carlescufi  fyi, submitted changes to openocd upstream
http://openocd.zylin.com/#/c/5634/

**Comment by carlescufi** [comment]
@MaureenHelm can you review this please?

**Comment by MaureenHelm** [comment]
> @MaureenHelm can you review this please?

It looks ok to me, but would like @galak to take a look.

**Comment by ssekar15** [comment]
@galak any feedback from you please?

**Comment by ssekar15** [comment]
@carlescufi Seems @galak has no time to review, Is it fine for you to merge PR as @MaureenHelm had accepted?

**Comment by carlescufi** [comment]
@MaureenHelm and @galak could you take a quick look?

**Comment by carlescufi** [comment]
@jettr @MulinChao could you please take a look?

**Comment by MulinChao** [comment]
> @jettr @MulinChao could you please take a look?

@carlescufi , sorry. I'm not familiar with Nu-Link. I will ask my colleague to review it.

**Comment by jettr** [comment]
I am also not familiar with this, but nothing obvious stands out to me. Looks good to me.

**Comment by MulinChao** [comment]
> > @jettr @MulinChao could you please take a look?
> 
> @carlescufi , sorry. I'm not familiar with Nu-Link. I will ask my colleague to review it.

CC @wschang0 who is the software leader of Nuvoton generic MCU products. 
@wschang0, could you take a look or assign someone familiar with this?

**Comment by ssekar15** [comment]
@ZaleYu Please review

**Comment by ssekar15** [comment]
@ccma1120 please review

**Comment by ZaleYu** [comment]
> @ZaleYu Please review

Looks good to me,

**Comment by ccma1120** [comment]
> @ccma1120 please review

it looks ok.

**Comment by galak** [comment]
@ssekar15 sorry for the late comment, can we look at rebasing this on the zephyr-20200722 branch.

**Comment by galak** [comment]
@ssekar15 looks like some nulink support has been merged upstream.  I've pulled in that in PR #33

**Comment by ssekar15** [comment]
@galak thanks, than I close this PR

**Pull request closed without merging**
